spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.198.224.127:3306/content?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: 123

xxl:
  job:
    admin: 
      addresses: http://116.198.224.127:18088/xxl-job-admin/
    executor:
      appname: course-publish-job
      address:
      ip:
      port: 10999
      logpath: /data/applogs/xxl-job-jobhandler
      logretentiondays: 30
    accessToken: default_token