spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.198.224.127:3306/orders?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: 123

xxl:
  job:
    admin: 
      addresses: http://116.198.224.127:8088/xxl-job-admin
    executor:
      appname: payresultnotify-job
      address: 
      ip: 
      port: 8989
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token